Repository danburonline/oscy-space, pull requests merged in 2021-05, with the labels that each got.

#4 Trying out a new project structure
  objects/primitives/cube.tsx
  pages/basic-cube/BasicCube.module.scss
  pages/basic-cube/index.tsx
  pages/index.module.scss
  pages/index.tsx
  styles/globals.scss
  styles/reset.scss
Labels: enhancement

#6 Adding a new components folder
  components/objects/primitives/cube.tsx
  pages/basic-cube/index.tsx
Labels: good first issue

#7 Adding physics with @react-three/cannon
  components/objects/primitives/cube.tsx
  components/objects/primitives/physicsCube.tsx
  package.json
  pages/index.tsx
  pages/physics/index.tsx
  yarn.lock
Labels: enhancement

#8 Adding TailwindCSS
  .gitignore
  components/atoms/BackHomeButton.tsx
  components/molecules/Card.tsx
  components/organisms/Cards.tsx
  components/organisms/Header.tsx
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/basic-cube/index.tsx
  pages/index.module.scss
  pages/index.tsx
  pages/physics-cube/index.tsx
  pages/physics/index.tsx
  postcss.config.js
  public/favicon.ico
  styles/globals.scss
  styles/reset.scss
  tailwind.config.js
  yarn.lock
Labels: enhancement

#9 Adding a 2nd Physics Scene
  components/objects/dynamic/InstancedSpheres.tsx
  components/objects/primitives/Box.tsx
  components/objects/primitives/Plane.tsx
  components/scenes/PhysicsExperimentScene.tsx
  package.json
  pages/basic-cube/index.tsx
  pages/index.tsx
  pages/physics-cube/index.tsx
  pages/physics-experiment/index.tsx
  public/imgs/textures/normals/carbon-normal.jpeg
  yarn.lock
Labels: enhancement

#11 Again adding the new physics example scene
  components/objects/dynamic/InstancedSpheres.tsx
  components/objects/primitives/Box.tsx
  components/objects/primitives/Plane.tsx
  components/scenes/PhysicsExperimentScene.tsx
  package.json
  pages/basic-cube/index.tsx
  pages/index.tsx
  pages/physics-cube/index.tsx
  pages/physics-experiment/index.tsx
  public/imgs/textures/normals/carbon-normal.jpeg
  yarn.lock
Labels: duplicate, enhancement

#12 Removing the Tailwind prefix + cleaning things
  .github/workflows/cloud-run.yml
  .prettierrc
  components/atoms/BackHomeButton.tsx
  components/molecules/Card.tsx
  components/objects/dynamic/InstancedSpheres.tsx
  components/objects/primitives/KinematicBox.tsx
  components/objects/primitives/MassCube.tsx
  components/objects/primitives/SimpleCube.tsx
  components/organisms/Cards.tsx
  components/organisms/Header.tsx
  components/scenes/PhysicsExperimentScene.tsx
  pages/404.tsx
  pages/basic-cube/index.tsx
  pages/index.tsx
  pages/physics-cube/index.tsx
  pages/physics-experiment/index.tsx
  tailwind.config.js
Labels: enhancement

#13 Oscy Space API
  package.json
  pages/_document.tsx
  pages/api/index.ts
  pages/api/rooms/index.ts
  pages/api/rooms/roomData.json
  pages/api/rooms/types.ts
  pages/index.tsx
  yarn.lock
Labels: enhancement

#16 Adding First-Person Controls
  components/objects/complex/Player.tsx
  components/scenes/FpvExampleScene.tsx
  pages/api/rooms/roomData.json
  pages/fpv-example/index.tsx
Labels: enhancement

#17 Added a basic scene for testing the ambient sound in stereo
  .gitattributes
  components/objects/complex/AmbientStereo.tsx
  components/scenes/AmbientSoundScene.tsx
  package.json
  pages/ambient-sound-stereo/index.tsx
  pages/api/rooms/roomData.json
  public/sounds/ambientSound.wav
  yarn.lock
Labels: enhancement
