Repository danburonline/oscy-space, pull requests merged in 2021-07, with the labels that each got.

#44 Finishing The Proof of Concept
  .babelrc
  components/objects/complex/AdjustedPlayer.tsx
  components/objects/data/tamina-mesh-collision.ts
  components/scenes/FinalTaminaTestScene.tsx
  package.json
  pages/api/rooms/roomData.json
  public/final-tamina-draco/Collider_v2.bin
  public/final-tamina-draco/Collider_v2.gltf
  yarn.lock
Labels: enhancement

#58 Basic Project Structure Setup For The MVP
  .eslintignore
  .eslintrc
  .github/pull_request_template.md
  .prettierignore
  .prettierrc
  next-env.d.ts
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/forest/index.tsx
  pages/gorge/index.tsx
  pages/index.tsx
  postcss.config.js
  src/components/atoms/ExampleComponent.tsx
  src/scenes/forest/Forest.tsx
  src/scenes/gorge/Gorge.tsx
  tsconfig.json
  yarn.lock
Labels: blocker, task

#60 Adding a New Styleguide
  pages/_document.tsx
  pages/index.tsx
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/site.webmanifest
  public/src/styleguide.ai
  tailwind.config.js
Labels: enhancement, task

#61 Adding a Basic Screen Design
  public/icons/arrow-back.svg
  public/icons/audio-off-icon.svg
  public/icons/audio-on-icon.svg
  public/icons/circle-large.svg
  public/icons/circle-medium.svg
  public/icons/circle-small-dot.svg
  public/icons/exit-room-arrow.svg
  public/icons/fullscreen-off-icon.svg
  public/icons/house-icon.svg
  public/logos/oscy-logo-mobile-blocker.svg
Labels: blocker, enhancement, task

#78 Feat/audio implentation
  package.json
  pages/forest/index.tsx
  pages/gorge/index.tsx
  src/components/AmbientPositionalSound.tsx
  src/components/AmbientStereoSound.tsx
  src/components/AudioButton.tsx
  src/components/FullScreenButton.tsx
  src/components/PointerLockButton.tsx
  src/components/SoundObject.tsx
  src/scenes/forest/Forest.tsx
  src/scenes/forest/utils/ForestSoundArray.ts
  src/scenes/gorge/Gorge.tsx
  src/scenes/gorge/utils/GorgeSoundArray.ts
  src/types/types.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement, feature, task

#81 Feat/audio tweaks
  src/components/AudioButton.tsx
  src/components/CollisionBox.tsx
  src/scenes/forest/Forest.tsx
  src/scenes/forest/utils/ForestSoundArray.ts
  src/scenes/gorge/Gorge.tsx
  src/scenes/gorge/components/Collider.tsx
  src/scenes/gorge/types/types.ts
  src/scenes/gorge/utils/GorgeSoundArray.ts
  src/scenes/gorge/utils/gorgeColliderBoxesArray.ts
  src/types/types.ts
  tailwind.config.js
Labels: enhancement

#82 Fix/sound array
  src/scenes/gorge/utils/gorgeSoundArray.ts
Labels: enhancement

#83 enhancement/removed visible meshes and helper from audio objects
  src/components/AmbientPositionalSound.tsx
  src/components/SoundObject.tsx
Labels: enhancement

#84 Adding The Final Mesh Colliders For The Gorge Scene
  src/components/CollisionBox.tsx
  src/components/Player.tsx
  src/scenes/gorge/Gorge.tsx
  src/scenes/gorge/utils/gorgeColliderBoxesArray.ts
  src/scenes/gorge/utils/gorgeSoundArray.ts
  src/types/types.ts
Labels: bug, enhancement, feature, task
